# =============================================================================
# Cloud Build Configuration - FAANG-Grade CI/CD Pipeline
# =============================================================================
# This pipeline includes:
# - Security scanning (Snyk, Trivy, SAST)
# - Code quality (linting, formatting)
# - Comprehensive testing (unit, integration)
# - Multi-stage Docker builds
# - Staged deployments with health checks
# =============================================================================

substitutions:
  _REGION: 'us-central1'
  _BACKEND_IMAGE: '${_REGION}-docker.pkg.dev/${PROJECT_ID}/portal/backend'
  _FRONTEND_IMAGE: '${_REGION}-docker.pkg.dev/${PROJECT_ID}/portal/frontend'
  _APPLY_WORKLOADS: 'false'  # set to 'true' to terraform apply workloads LB/IAP

options:
  logging: CLOUD_LOGGING_ONLY
  machineType: 'E2_HIGHCPU_8'
  dynamic_substitutions: true

availableSecrets:
  secretManager:
    - versionName: projects/${PROJECT_ID}/secrets/PORTAL_WORKLOADS_TFVARS/versions/latest
      env: TFVARS_WORKLOADS
    - versionName: projects/${PROJECT_ID}/secrets/PORTAL_AUTH_TOKEN/versions/latest
      env: PORTAL_AUTH_TOKEN

steps:
  # ==========================================================================
  # Stage 1: Security Scanning (Parallel)
  # ==========================================================================
  - name: 'aquasec/trivy'
    id: 'trivy-scan-backend'
    entrypoint: 'sh'
    args:
      - '-c'
      - |
        trivy fs --exit-code 1 --severity HIGH,CRITICAL --ignore-unfixed backend/
    waitFor: ['-']

  - name: 'returntocorp/semgrep'
    id: 'semgrep-sast'
    args: ['semgrep', 'scan', '--config', 'auto', '--error']
    waitFor: ['-']

  - name: 'node:20-slim'
    id: 'snyk-test'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        if [ -n "$ _SNYK_TOKEN" ]; then
          npm install -g snyk
          snyk auth "$ _SNYK_TOKEN"
          snyk test --severity-threshold=high frontend/
          snyk test --severity-threshold=high backend/
        else
          echo "Snyk token not configured, skipping"
        fi
    waitFor: ['-']

  # ==========================================================================
  # Stage 2: Code Quality (Parallel)
  # ==========================================================================
  - name: 'python:3.11-slim'
    id: 'lint-backend'
    dir: 'backend'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        pip install --quiet ruff bandit
        echo "=== Running ruff linter ==="
        ruff check . || exit 1
        echo "=== Running bandit security linter ==="
        bandit -r . -ll -ii --exclude ./tests || exit 1
    waitFor: ['-']

  - name: 'node:20-slim'
    id: 'lint-frontend'
    dir: 'frontend'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        npm ci --silent
        echo "=== Running ESLint ==="
        npm run lint || exit 1
        echo "=== Checking types ==="
        npx tsc --noEmit || exit 1
    waitFor: ['-']

  # ==========================================================================
  # Stage 3: Testing
  # ==========================================================================
  - name: 'python:3.11-slim'
    id: 'test-backend'
    dir: 'backend'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        pip install --quiet -r requirements.txt
        echo "=== Running unit tests ==="
        python -m pytest tests/ \
          --cov=. \
          --cov-report=term-missing \
          --cov-report=xml:coverage.xml \
          --junitxml=test-results.xml \
          -v
    waitFor: ['lint-backend']

  - name: 'node:20-slim'
    id: 'test-frontend'
    dir: 'frontend'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        npm ci --silent
        echo "=== Running tests with coverage ==="
        npm run test -- --run --coverage --reporter=junit --outputFile=test-results.xml
    waitFor: ['lint-frontend']

  # ==========================================================================
  # Stage 4: Terraform Validation
  # ==========================================================================
  - name: 'hashicorp/terraform:1.7'
    id: 'terraform-validate'
    dir: 'terraform/01-foundation'
    entrypoint: 'sh'
    args:
      - '-c'
      - |
        terraform init -backend=false
        terraform validate
        terraform fmt -check -recursive
    waitFor: ['-']

  - name: 'instrumenta/conftest'
    id: 'terraform-policy-check'
    args: ['test', 'terraform/', '--policy', 'policies/terraform']
    waitFor: ['terraform-validate']

  # ==========================================================================
  # Stage 4b: Terraform Plan Workloads (/lz LB + IAP)
  # ==========================================================================
  - name: 'hashicorp/terraform:1.7'
    id: 'terraform-plan-workloads'
    dir: 'terraform/04-workloads'
    entrypoint: 'bash'
    secretEnv: ['TFVARS_WORKLOADS']
    args:
      - '-c'
      - |
        echo "=== Writing tfvars from Secret Manager (PORTAL_WORKLOADS_TFVARS) ==="
        echo "$TFVARS_WORKLOADS" > ci.tfvars
        terraform init -backend=false
        terraform fmt -check -recursive
        terraform plan -var-file=ci.tfvars -out=tfplan.out
    waitFor: ['terraform-validate']

  # ==========================================================================
  # Stage 4c: Terraform Apply Workloads (gated by _APPLY_WORKLOADS=true)
  # ==========================================================================
  - name: 'hashicorp/terraform:1.7'
    id: 'terraform-apply-workloads'
    dir: 'terraform/04-workloads'
    entrypoint: 'bash'
    secretEnv: ['TFVARS_WORKLOADS']
    args:
      - '-c'
      - |
        if [ "${_APPLY_WORKLOADS}" != "true" ]; then
          echo "_APPLY_WORKLOADS != true; skipping terraform apply."
          exit 0
        fi
        echo "$TFVARS_WORKLOADS" > ci.tfvars
        terraform init -backend=false
        terraform apply -auto-approve tfplan.out
    waitFor: ['terraform-plan-workloads']

  # ==========================================================================
  # Stage 5: Build Container Images (Parallel)
  # ==========================================================================
  - name: 'gcr.io/cloud-builders/docker'
    id: 'build-backend'
    args:
      - 'build'
      - '--target=production'
      - '--build-arg=BUILD_DATE=${BUILD_ID}'
      - '--build-arg=VCS_REF=${COMMIT_SHA}'
      - '--cache-from=${_BACKEND_IMAGE}:latest'
      - '-t=${_BACKEND_IMAGE}:${COMMIT_SHA}'
      - '-t=${_BACKEND_IMAGE}:${SHORT_SHA}'
      - '-t=${_BACKEND_IMAGE}:latest'
      - '-f=backend/Dockerfile'
      - 'backend/'
    waitFor: ['test-backend']

  # Generate SBOM from source for backend and scan with Grype (fail on high)
  - name: 'anchore/syft:latest'
    id: 'sbom-backend'
    entrypoint: 'sh'
    dir: 'backend'
    args:
      - '-c'
      - |
        syft dir:. -o spdx-json=../backend-sbom.json
    waitFor: ['test-backend']

  - name: 'anchore/grype:latest'
    id: 'grype-backend-sbom'
    entrypoint: 'sh'
    args:
      - '-c'
      - |
        grype sbom:backend-sbom.json --fail-on high
    waitFor: ['sbom-backend']

  - name: 'gcr.io/cloud-builders/docker'
    id: 'build-frontend'
    args:
      - 'build'
      - '--target=production'
      - '--build-arg=VITE_API_URL=/api'
      - '--build-arg=BUILD_DATE=${BUILD_ID}'
      - '--build-arg=VCS_REF=${COMMIT_SHA}'
      - '--cache-from=${_FRONTEND_IMAGE}:latest'
      - '-t=${_FRONTEND_IMAGE}:${COMMIT_SHA}'
      - '-t=${_FRONTEND_IMAGE}:${SHORT_SHA}'
      - '-t=${_FRONTEND_IMAGE}:latest'
      - '-f=frontend/Dockerfile'
      - 'frontend/'
    waitFor: ['test-frontend']

  # Generate SBOM from source for frontend and scan with Grype (fail on high)
  - name: 'anchore/syft:latest'
    id: 'sbom-frontend'
    entrypoint: 'sh'
    dir: 'frontend'
    args:
      - '-c'
      - |
        syft dir:. -o spdx-json=../frontend-sbom.json
    waitFor: ['test-frontend']

  - name: 'anchore/grype:latest'
    id: 'grype-frontend-sbom'
    entrypoint: 'sh'
    args:
      - '-c'
      - |
        grype sbom:frontend-sbom.json --fail-on high
    waitFor: ['sbom-frontend']

  # ==========================================================================
  # Stage 6: Container Security Scanning
  # ==========================================================================
  - name: 'aquasec/trivy'
    id: 'scan-backend-image'
    entrypoint: 'sh'
    args:
      - '-c'
      - |
        trivy image \
          --exit-code 1 \
          --severity CRITICAL \
          --ignore-unfixed \
          ${_BACKEND_IMAGE}:${COMMIT_SHA} || exit 1
    waitFor: ['build-backend']

  - name: 'aquasec/trivy'
    id: 'scan-frontend-image'
    entrypoint: 'sh'
    args:
      - '-c'
      - |
        trivy image \
          --exit-code 1 \
          --severity CRITICAL \
          --ignore-unfixed \
          ${_FRONTEND_IMAGE}:${COMMIT_SHA} || exit 1
    waitFor: ['build-frontend']

  # ==========================================================================
  # Stage 7: Push to Artifact Registry
  # ==========================================================================
  - name: 'gcr.io/cloud-builders/docker'
    id: 'push-backend'
    args:
      - 'push'
      - '--all-tags'
      - '${_BACKEND_IMAGE}'
    waitFor: ['scan-backend-image']

  - name: 'gcr.io/cloud-builders/docker'
    id: 'push-frontend'
    args:
      - 'push'
      - '--all-tags'
      - '${_FRONTEND_IMAGE}'
    waitFor: ['scan-frontend-image']

  # ==========================================================================
  # Stage 8: Deploy to Staging
  # ==========================================================================
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    id: 'deploy-backend-staging'
    entrypoint: 'gcloud'
    args:
      - 'run'
      - 'deploy'
      - 'portal-backend-staging'
      - '--image=${_BACKEND_IMAGE}:${COMMIT_SHA}'
      - '--region=${_REGION}'
      - '--platform=managed'
      - '--no-allow-unauthenticated'
      - '--service-account=portal-backend@${PROJECT_ID}.iam.gserviceaccount.com'
      - '--set-env-vars=ENVIRONMENT=staging,GCP_PROJECT_ID=${PROJECT_ID},PORTAL_AUTH_TOKEN=${PORTAL_AUTH_TOKEN}'
      - '--min-instances=1'
      - '--max-instances=10'
      - '--memory=512Mi'
      - '--cpu=1'
      - '--timeout=60s'
      - '--concurrency=80'
    waitFor: ['push-backend']

  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    id: 'deploy-frontend-staging'
    entrypoint: 'gcloud'
    args:
      - 'run'
      - 'deploy'
      - 'portal-frontend-staging'
      - '--image=${_FRONTEND_IMAGE}:${COMMIT_SHA}'
      - '--region=${_REGION}'
      - '--platform=managed'
      - '--no-allow-unauthenticated'
      - '--min-instances=1'
      - '--max-instances=10'
      - '--memory=256Mi'
      - '--cpu=1'
      - '--timeout=30s'
    waitFor: ['push-frontend']

  # ==========================================================================
  # Stage 9: Health Check Staging
  # ==========================================================================
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    id: 'verify-staging'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        echo "=== Waiting for deployment to stabilize ==="
        sleep 30

        BACKEND_URL=$(gcloud run services describe portal-backend-staging \
          --region=${_REGION} \
          --format='value(status.url)')

        echo "=== Testing backend health endpoint ==="
        for i in {1..5}; do
          if curl -sf "$BACKEND_URL/health" > /dev/null; then
            echo "Health check passed!"
            exit 0
          fi
          echo "Attempt $i failed, retrying..."
          sleep 10
        done

        echo "Health check failed after 5 attempts"
        exit 1
    waitFor: ['deploy-backend-staging', 'deploy-frontend-staging']

  # ==========================================================================
  # Stage 10: Artifact Archiving & Signing
  # ==========================================================================
  # Signing with Cosign (requires KMS key access)
  # - name: 'gcr.io/projectsigstore/cosign:latest'
  #   id: 'sign-images'
  #   args: ['sign', '--key', 'gcpkms://projects/${PROJECT_ID}/locations/${_REGION}/keyRings/portal-ring/cryptoKeys/portal-sig-key', '${_BACKEND_IMAGE}:${COMMIT_SHA}', '${_FRONTEND_IMAGE}:${COMMIT_SHA}']
  #   waitFor: ['push-backend', 'push-frontend']

  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    id: 'archive-artifacts'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        gsutil cp backend-sbom.json gs://${PROJECT_ID}-artifacts/sboms/backend/${COMMIT_SHA}.json
        gsutil cp frontend-sbom.json gs://${PROJECT_ID}-artifacts/sboms/frontend/${COMMIT_SHA}.json
    waitFor: ['grype-backend-sbom', 'grype-frontend-sbom']

  # ==========================================================================
  # Stage 11: Production Deployment (Manual Approval Recommended)
  # ==========================================================================
  # This step is commented out to represent a gated promotion.
  # Use Cloud Deploy or a manual approval step in Cloud Build trigger for this.
  # - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  #   id: 'deploy-prod'
  #   entrypoint: 'gcloud'
  #   args:
  #     - 'run'
  #     - 'deploy'
  #     - 'portal-backend-prod'
  #     - '--image=${_BACKEND_IMAGE}:${COMMIT_SHA}'
  #   waitFor: ['verify-staging']

images:
  - '${_BACKEND_IMAGE}:${COMMIT_SHA}'
  - '${_BACKEND_IMAGE}:latest'
  - '${_FRONTEND_IMAGE}:${COMMIT_SHA}'
  - '${_FRONTEND_IMAGE}:latest'

timeout: '1800s'  # 30 minutes max

tags:
  - 'gcp-cloud'
  - 'portal'
  - 'ci-cd'
